name: Typescript Compiler Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install npm packages
        run: npm install

      - name: Typescript validation check
        run: npm run build
